kind: Deployment
apiVersion: apps/v1
metadata:
  name: avins1-deployment
  labels:
    app: hackazon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hackazon
  template:
    metadata:
      labels:
        app: hackazon
    spec:
      containers:
      - name: hackazon
        image: ianwijaya/hackazon
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: avihackazoning1-lb
  labels:
    svc: avihackazoning1-lb
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: hackazon
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: avins2ingress
spec:
  ingressClassName: avi-lb
  rules:
  - host: avins1-1.ako.avidemo.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: avihackazoning1-lb
            port:
              number: 80
  - host: avins1-2.ako.avidemo.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: avihackazoning1-lb
            port:
              number: 80
  - host: avins1-5.ako.avidemo.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: avihackazoning1-lb
            port:
              number: 80
  - host: avins1-6.ako.avidemo.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: avihackazoning1-lb
            port:
              number: 80
  - host: avins1-7.ako.avidemo.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: avihackazoning1-lb
            port:
              number: 80
  - host: avins1-9.ako.avidemo.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: avihackazoning1-lb
            port:
              number: 80
  - host: avins1-10.ako.avidemo.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: avihackazoning1-lb
            port:
              number: 80                                                                   
  - host: avins1-11.ako.avidemo.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: avihackazoning1-lb
            port:
              number: 80   
  - host: avins1-12.ako.avidemo.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: avihackazoning1-lb
            port:
              number: 80   
  - host: avins1-13.ako.avidemo.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: avihackazoning1-lb
            port:
              number: 80   
  - host: avins1-14.ako.avidemo.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: avihackazoning1-lb
            port:
              number: 80   
  - host: avins1-15.ako.avidemo.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: avihackazoning1-lb
            port:
              number: 80   
  - host: avins1-16.ako.avidemo.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: avihackazoning1-lb
            port:
              number: 80   
  - host: avins1-17.ako.avidemo.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: avihackazoning1-lb
            port:
              number: 80                                                                                                     